[platformio]
default_envs = esp32s3_2mb

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
; Do not add lib_deps for TinyUSB. esp_tinyusb is pulled by main/idf_component.yml.

[env:esp32s3_2mb]
board_build.flash_size = 2MB
board_upload.flash_size = 2MB
board_build.partitions = partitions_2MB.csv

[env:esp32s3_8mb]
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions_8MB.csv
